name: Build

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Cargo cache
        uses: Swatinem/rust-cache@v2
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --no-deps -- -D warnings
      - uses: actions/setup-python@v6
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: '**/pyproject.toml'
      - run: pip install -e ./tsar-py
      - run: pip install pylint black mypy
      - run: black --check --config ./tsar-py/pyproject.toml tsar-py
      - run: mypy --config-file ./tsar-py/pyproject.toml tsar-py
      - run: pylint --rcfile tsar-py/pyproject.toml tsar-py

  build:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@v5
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Cargo cache
        uses: Swatinem/rust-cache@v2
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release
      - uses: actions/setup-python@v6
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: '**/pyproject.toml'
      - run: pip install -e ./tsar-py
