name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Cache cargo states
        uses: actions/cache@v3
        env:
          cache-name: cargo_states_lint
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
            target
          key: ubuntu-latest-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            ubuntu-latest-
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --no-deps -- -D warnings
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'
          cache-dependency-path: '**/pyproject.toml'
      - run: pip install -e ./tsar-py
      - run: pip install pylint black mypy
      - run: black --check --config ./tsar-py/pyproject.toml tsar-py
      - run: mypy --config-file ./tsar-py/pyproject.toml tsar-py
      - run: pylint --rcfile tsar-py/pyproject.toml tsar-py

  build:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Cache cargo states
        uses: actions/cache@v3
        env:
          cache-name: cargo_states
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
            target
          key: ubuntu-latest-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            ubuntu-latest-
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'
          cache-dependency-path: '**/pyproject.toml'
      - run: pip install -e ./tsar-py
