name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Cache cargo states
        uses: actions/cache@v3
        env:
          cache-name: cargo_states
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
            target
          key: ubuntu-latest-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            ubuntu-latest-
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --release
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --no-deps --release -- -D warnings
